# Generated by Django 3.0.6 on 2020-06-01 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0002_auto_20200601_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogHomePage',
            new_name='BlogIndexPage',
        ),
    ]
