# Generated by Django 3.0.6 on 2020-06-29 03:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzlepagegalleryimage_puzzlepostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepostpage',
            name='answer',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
