# Generated by Django 3.0.7 on 2020-07-01 02:25

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_puzzlepostpage_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlepostpage',
            name='answer',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
