# Generated by Django 3.0.7 on 2020-07-01 03:25

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_auto_20200701_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlepostpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
